### ISSUE TITLE
Build a Stream Source with Event Timestamps code snippet does not include allowedLateness(2000)

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet-reference-manual#130]
In section `5.11.1. Source Builder` in `Build a Stream Source with Event Timestamps` part there is code snippet and under him is sentence `Note the line allowedLateness(2000).`. However there is no occurence of `allowedLateness(2000)` - it seems as something which was in that snippet but was removed. Sentence should be fixed.

**Comment by cangencer** [comment]
Looks like this was already removed as part of #139, closing it.
