### ISSUE TITLE
Lossless Recovery part in manual is missing a lot of details

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet-reference-manual#131]
Lossless Recovery section in the manual is missing several important details

* Missing information about the need to enable REST API to use Lossless Recovery
* Missing information about need to set to passive mode, do an orderly shutdown and then start up again

**Comment by mtopolnik** [comment]
Since there's no need to manually put the cluster into the PASSIVE state, this isn't documented as a requirement.

**Comment by gurbuzali** [comment]
yes we've fixed the issue related restarting without setting to PASSIVE state via https://github.com/hazelcast/hazelcast-jet/pull/1277
