### ISSUE TITLE
Issue in "Implementing DAG in Jet"

### ISSUE THREAD

**Issue by mukul4u2005** [hazelcast/hazelcast-jet-reference-manual#4]
final Pattern delimiter = Pattern.compile("\\W+");
Vertex tokenizer = dag.newVertex("tokenizer",
      flatMap((String line) -> traverseArray(delimiter.split(line.toLowerCase()))
                                  .filter(word -> !word.isEmpty()))
);

Should be 

Vertex tokenizer = dag.newVertex("tokenizer", 
		    flatMap((Entry<Integer, String> line) -> 
		           traverseArray(line.getValue().toLowerCase().split("\\W+"))
		          .filter(word -> !word.isEmpty()))
		);

**Comment by cangencer** [comment]
Thanks for reporting, this is now fixed.
