### ISSUE TITLE
The watermark policy page could use some diagrams

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-jet-reference-manual#66]
I believe [different policies](http://docs.hazelcast.org/docs/jet/0.5.1/manual/Expert_Zone_--_The_Core_API/WatermarkPolicy.html) could be simpler to explain and understand with some pictures. 

I think we could have 1 diagram to illustrate the concept of watermarking (inserting WM into a stream of data) and then a diagram for each policy described.

**Comment by mtopolnik** [comment]
Since we decided to keep the watermark policy as a Core API-only concern, this has a low priority.
