### ISSUE TITLE
Word Count example causes ClassCastException.

### ISSUE THREAD

**Issue by Serdaro** [hazelcast/hazelcast-jet-reference-manual#7]
The example code lines in the section "Implementing DAIG in Jet" should be synced with the Jet code samples repo.

**Comment by mtopolnik** [comment]
This commit should fix all the issues:

https://github.com/hazelcast/hazelcast-jet-reference-manual/commit/3421cafb65230db81bb9223183c4ca1a62953b9c

In addition to that we now have a Java class with the complete sample so it can be compiled and run to verify its correctness:

https://github.com/hazelcast/hazelcast-jet-code-samples/blob/0.3-maintenance/core/wordcount/src/main/java/WordCountRefMan.java

The above is on the `0.3-maintenance` branch and the same file was added to `master`.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-jet-reference-manual/commit/3421cafb65230db81bb9223183c4ca1a62953b9c
