### ISSUE TITLE
withFixedLag still reference

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet-reference-manual#75]
In http://docs.hazelcast.org/docs/jet/0.6/manual/#predefined-watermark-policies
fixed lag is http://docs.hazelcast.org/docs/jet/0.6/manual/#with-fixed-lag

But this method `withFixedLag` no longer exists, now I think called `withLimitingLag`

**Comment by mtopolnik** [comment]
Fixed: https://github.com/hazelcast/hazelcast-jet-reference-manual/commit/17afdeaca83651e73ededeefba8515653ff1de03
